-- DROP TABLE IF EXISTS ARTICLE;

create table ARTICLE
(
    ARTICLE_ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    TITLE           VARCHAR(100)    NOT NULL,
    CONTENT         LONGTEXT        NOT NULL,
    THUMBNAIL       VARCHAR(300)    NOT NULL,
    CREATED_AT      DATETIME default now(),
    CONSTRAINT FK_ARTICLE_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

