DROP TABLE IF EXISTS COMMUNITY_COMMENT;
DROP TABLE IF EXISTS FILE_REPO;
DROP TABLE IF EXISTS COMMUNITY;

# 커뮤니티
CREATE TABLE COMMUNITY
(
    COMMUNITY_ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    M_NO            BIGINT,
    TITLE           VARCHAR(100),
    CONTENT         TEXT,
    TAG             VARCHAR(50),
    VIEWS           INT default 0,
    IS_DELETED      TINYINT(1), -- 0:존재 1:삭제
    UPDATED_AT      DATETIME default now(),
    CREATED_AT      DATETIME default now(),

    CONSTRAINT FK_COMMUNITY_MEMBER FOREIGN KEY (M_NO) REFERENCES member(mno)
);

# 첨부파일
CREATE TABLE FILE_REPO
(
      FILE_ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
      COMMUNITY_ID      BIGINT,
      FILE_NAME         VARCHAR(255),
      FILE_PATH         VARCHAR(255),
      FILE_TYPE         CHAR(5),
      CREATED_AT        DATETIME DEFAULT now(),

      CONSTRAINT FK_FILE_REPO_COMMUNITY FOREIGN KEY (COMMUNITY_ID) REFERENCES COMMUNITY(COMMUNITY_ID) ON DELETE CASCADE
);



