DROP TABLE IF EXISTS COMMUNITY_COMMENT;
DROP TABLE IF EXISTS FILE_REPO;
DROP TABLE IF EXISTS COMMUNITY;
CREATE TABLE COMMUNITY
(
    COMMUNITY_ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    TITLE           VARCHAR(100),
    CONTENT         TEXT,
    TAG             VARCHAR(50),
    IS_DELETED      TINYINT(1), -- 0:존재 1:삭제
    UPDATED_AT      DATETIME default now(),
    CREATED_AT      DATETIME default now(),

    CONSTRAINT FK_COMMUNITY_MEMBER FOREIGN KEY (USER_ID) REFERENCES member(mno)
);