drop table if exists UNIVERSITY;
create table UNIVERSITY(
    UVS_ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(50),
    UVS_LAT     DECIMAL(10, 7),
    UVS_LONG    DECIMAL(10, 7),
    ADDRESS     VARCHAR(300)
#     SUBWAYS     VARCHAR(255), # '|'를 구분자로 1.5km 이내 전철 코드 문자열
#     TYPE        VARCHAR(50)
);

drop table if exists UNIV_SUBWAY;
create table UNIV_SUBWAY(
    US_ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    UVS_ID   BIGINT,
    SBW_CODE CHAR(5),
    CONSTRAINT FK_UNIV_SUBWAY_UNIVERSITY FOREIGN KEY (UVS_ID) REFERENCES UNIVERSITY(UVS_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UNIV_SUBWAY_SUBWAY FOREIGN KEY (SBW_CODE) REFERENCES SUBWAY(CODE) ON DELETE CASCADE
);

